/**
 * Generates the JSX runtime's refresh copies, `src/jsx/refresh-copies.ts`:
 * the refresh code for each number of bindings, written out many times, so
 * that a shape of bindings can have code, and V8 feedback, of its own (see
 * `createRefreshBuilder` in `src/jsx/refresh-builder.ts`). The output is not
 * checked in. `npm install` runs this, and so do `npm run dev`, `build`,
 * `test` and `bench`, so it is current wherever they are used.
 *
 * Usage:  npm run generate-refresh-copies
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/** Where the generated module is saved. Not checked in: see `.gitignore`. */
const REFRESH_COPIES_PATH = fileURLToPath(new URL('../src/jsx/refresh-copies.ts', import.meta.url));

/**
 * Copies of each refresh function: the first shared, the rest each for one
 * shape of its own. More let more shapes of the same size have code of their
 * own.
 */
const COPIES = 17;

/** Refresh functions are written out for up to this many bindings; more use a loop. */
const MAX_BINDINGS = 6;

writeFileSync(REFRESH_COPIES_PATH, refreshCopiesSource());
console.log(`▸ ${REFRESH_COPIES_PATH}`);

// ---------------------------------------------------------------------------
// The generated source
// ---------------------------------------------------------------------------

/**
 * The source of `refresh-copies.ts`: {@link COPIES} copies of a refresh
 * function for each number of bindings from 1 to {@link MAX_BINDINGS}. The
 * copies are identical, and each is separate code: V8 keeps its feedback per
 * function in source, so an element shape given a copy of its own gets call
 * sites and property stores of its own.
 */
function refreshCopiesSource(): string {
    const lines: string[] = [
        '// Generated by `npm run generate-refresh-copies` from `scripts/generate-refresh-copies.ts`, on',
        '// install and before dev, build, test and bench. Not checked in; do not edit by hand.',
        '//',
        `// ${COPIES} identical copies of a refresh function for each number of bindings, 1 to ${MAX_BINDINGS}.`,
        '// Each is separate code, so each keeps its own V8 feedback: an element shape given',
        '// a copy of its own has call sites and property stores of its own, and V8 inlines',
        '// its getters and writes. See `createRefreshBuilder` in `refresh-builder.ts`.',
        '//',
        '// In a stack trace, `refresh3Copy1` is the refresh method of an element with three',
        '// bindings, in copy 1, and the line names the binding: `g0()` is the first.',
        '',
        'import { readCounter } from \'../read-counter\';',
        'import type { RefreshMethod } from \'../scene-methods\';',
        'import { SKIP_DESCENDANTS } from \'../skip-descendants\';',
        '',
        '/** Reads one binding. */',
        'export type Getter = () => unknown;',
        '',
        '/** Writes one binding\'s value to the element. */',
        'export type Writer = (el: unknown, value: unknown) => void;',
        '',
        '/** How one binding is written: a property name, assigned, or a writer, called. */',
        'export type Write = string | Writer;',
        '',
        '/**',
        ' * Makes one element\'s refresh method. Bit `i` of `changes` is set when binding',
        ' * `i` is written only on change, compared with the last value written, which',
        ' * starts as `unset`. With `hasVisible`, binding 0 is `visible`: when false,',
        ' * the rest are skipped, and one read is counted.',
        ' */',
        'export type RefreshCopy = (',
        '    el: Record<string, unknown>, getters: readonly Getter[], writes: readonly Write[], changes: number, hasVisible: boolean,',
        '    unset: unknown,',
        ') => RefreshMethod;',
        '',
        '/** Copies of the refresh function for `n` bindings, at index `n`. Copy 0 is shared. */',
        'export const REFRESH_COPIES: readonly (readonly RefreshCopy[])[] = [',
        '    [],',
    ];
    for (let n = 1; n <= MAX_BINDINGS; n++) {
        lines.push(`    [`);
        for (let k = 0; k < COPIES; k++) lines.push(`        make${upperFirst(copyName(n, k))},`);
        lines.push('    ],');
    }
    lines.push('];');
    for (let n = 1; n <= MAX_BINDINGS; n++) {
        for (let k = 0; k < COPIES; k++) lines.push('', ...copySource(n, k));
    }
    return `${lines.join('\n')}\n`;
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

/** The name of copy `k` of the refresh method for `n` bindings, as stack traces show it. */
function copyName(n: number, k: number): string {
    return `refresh${n}Copy${k}`;
}

function upperFirst(name: string): string {
    return name[0].toUpperCase() + name.slice(1);
}

function copySource(n: number, k: number): string[] {
    const name = copyName(n, k);
    const lines = [
        `function make${upperFirst(name)}(`,
        '    el: Record<string, unknown>, getters: readonly Getter[], writes: readonly Write[], changes: number, hasVisible: boolean,',
        '    unset: unknown,',
        '): RefreshMethod {',
    ];
    for (let i = 0; i < n; i++) lines.push(`    const g${i} = getters[${i}];`);
    for (let i = 0; i < n; i++) lines.push(`    const w${i} = writes[${i}];`);
    for (let i = 0; i < n; i++) lines.push(`    let l${i} = unset;`);
    lines.push(`    const ${name}: RefreshMethod = () => {`);
    lines.push(n === 1
        ? '        if (readCounter.isCounting) readCounter.count++;'
        : `        if (readCounter.isCounting) readCounter.count += hasVisible ? 1 : ${n};`);
    for (let i = 0; i < n; i++) {
        const bit = 1 << i;
        lines.push(
            `        const v${i} = g${i}();`,
            `        if ((changes & ${bit}) === 0 || v${i} !== l${i}) {`,
            `            if ((changes & ${bit}) !== 0) l${i} = v${i};`,
            `            if (typeof w${i} === 'string') {`,
            `                el[w${i}] = v${i};`,
            '            }',
            '            else {',
            `                w${i}(el, v${i});`,
            '            }',
            '        }',
        );
        if (i === 0 && n === 1) lines.push('        if (hasVisible && !v0) return SKIP_DESCENDANTS;');
        if (i === 0 && n > 1) {
            lines.push(
                '        if (hasVisible) {',
                '            if (!v0) return SKIP_DESCENDANTS;',
                `            if (readCounter.isCounting) readCounter.count += ${n - 1};`,
                '        }',
            );
        }
    }
    lines.push('    };', `    return ${name};`, '}');
    return lines;
}
